/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *label1;
  GtkWidget *label56;
  GtkWidget *bt_login_adh;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label57;
  GtkWidget *bt_quitter_adh;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image36;
  GtkWidget *label90;
  GtkWidget *image34;
  GtkWidget *label_mdp_inc;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 320, 72);
  gtk_widget_set_size_request (entry3, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed1), entry4, 320, 144);
  gtk_widget_set_size_request (entry4, 168, 35);
  gtk_entry_set_visibility (GTK_ENTRY (entry4), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label1 = gtk_label_new (_("username:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 208, 72);
  gtk_widget_set_size_request (label1, 96, 41);

  label56 = gtk_label_new (_("password:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed1), label56, 208, 144);
  gtk_widget_set_size_request (label56, 112, 40);

  bt_login_adh = gtk_button_new ();
  gtk_widget_show (bt_login_adh);
  gtk_fixed_put (GTK_FIXED (fixed1), bt_login_adh, 520, 408);
  gtk_widget_set_size_request (bt_login_adh, 96, 40);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (bt_login_adh), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox28), label57, FALSE, FALSE, 0);

  bt_quitter_adh = gtk_button_new ();
  gtk_widget_show (bt_quitter_adh);
  gtk_fixed_put (GTK_FIXED (fixed1), bt_quitter_adh, 184, 416);
  gtk_widget_set_size_request (bt_quitter_adh, 96, 40);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (bt_quitter_adh), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image36 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox33), image36, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("Close"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox33), label90, FALSE, FALSE, 0);

  image34 = create_pixmap (window1, "chayma.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed1), image34, 128, 192);
  gtk_widget_set_size_request (image34, 584, 320);

  label_mdp_inc = gtk_label_new (_("."));
  gtk_widget_show (label_mdp_inc);
  gtk_fixed_put (GTK_FIXED (fixed1), label_mdp_inc, 304, 200);
  gtk_widget_set_size_request (label_mdp_inc, 216, 16);

  g_signal_connect ((gpointer) bt_login_adh, "clicked",
                    G_CALLBACK (on_bt_login_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_quitter_adh, "clicked",
                    G_CALLBACK (on_bt_quitter_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label56, "label56");
  GLADE_HOOKUP_OBJECT (window1, bt_login_adh, "bt_login_adh");
  GLADE_HOOKUP_OBJECT (window1, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window1, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, label57, "label57");
  GLADE_HOOKUP_OBJECT (window1, bt_quitter_adh, "bt_quitter_adh");
  GLADE_HOOKUP_OBJECT (window1, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (window1, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (window1, image36, "image36");
  GLADE_HOOKUP_OBJECT (window1, label90, "label90");
  GLADE_HOOKUP_OBJECT (window1, image34, "image34");
  GLADE_HOOKUP_OBJECT (window1, label_mdp_inc, "label_mdp_inc");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *bt_logout_espace_adh;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label53;
  GtkWidget *bt_gest_rdv_staff_adh;
  GtkWidget *bt_inscri_seance_adh;
  GtkWidget *bt_gest_don_adh;
  GtkWidget *label2;
  GtkWidget *image35;
  GtkWidget *bt_profil_adh;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  bt_logout_espace_adh = gtk_button_new ();
  gtk_widget_show (bt_logout_espace_adh);
  gtk_fixed_put (GTK_FIXED (fixed2), bt_logout_espace_adh, 328, 464);
  gtk_widget_set_size_request (bt_logout_espace_adh, 120, 56);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (bt_logout_espace_adh), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Logout"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox25), label53, FALSE, FALSE, 0);

  bt_gest_rdv_staff_adh = gtk_button_new_with_mnemonic (_("Gestion des RDV avec staff m\303\251dical"));
  gtk_widget_show (bt_gest_rdv_staff_adh);
  gtk_fixed_put (GTK_FIXED (fixed2), bt_gest_rdv_staff_adh, 264, 408);
  gtk_widget_set_size_request (bt_gest_rdv_staff_adh, 248, 37);

  bt_inscri_seance_adh = gtk_button_new_with_mnemonic (_("Inscription de s\303\251ance"));
  gtk_widget_show (bt_inscri_seance_adh);
  gtk_fixed_put (GTK_FIXED (fixed2), bt_inscri_seance_adh, 264, 352);
  gtk_widget_set_size_request (bt_inscri_seance_adh, 248, 37);

  bt_gest_don_adh = gtk_button_new_with_mnemonic (_("Gestion des donn\303\251es"));
  gtk_widget_show (bt_gest_don_adh);
  gtk_fixed_put (GTK_FIXED (fixed2), bt_gest_don_adh, 264, 296);
  gtk_widget_set_size_request (bt_gest_don_adh, 248, 37);

  label2 = gtk_label_new (_("Bienvenue dans l'espace adh\303\251rant "));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 240, 176);
  gtk_widget_set_size_request (label2, 296, 64);
  gtk_misc_set_alignment (GTK_MISC (label2), 0.5, 0.52);

  image35 = create_pixmap (window2, "chayma2.png");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed2), image35, 176, 16);
  gtk_widget_set_size_request (image35, 424, 176);

  bt_profil_adh = gtk_button_new_with_mnemonic (_("Afficher mon profil"));
  gtk_widget_show (bt_profil_adh);
  gtk_fixed_put (GTK_FIXED (fixed2), bt_profil_adh, 264, 240);
  gtk_widget_set_size_request (bt_profil_adh, 248, 37);

  g_signal_connect ((gpointer) bt_logout_espace_adh, "clicked",
                    G_CALLBACK (on_bt_logout_espace_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_gest_rdv_staff_adh, "clicked",
                    G_CALLBACK (on_bt_gest_rdv_staff_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_inscri_seance_adh, "clicked",
                    G_CALLBACK (on_bt_inscri_seance_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_gest_don_adh, "clicked",
                    G_CALLBACK (on_bt_gest_don_ad_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_profil_adh, "clicked",
                    G_CALLBACK (on_bt_profil_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, bt_logout_espace_adh, "bt_logout_espace_adh");
  GLADE_HOOKUP_OBJECT (window2, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window2, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window2, image25, "image25");
  GLADE_HOOKUP_OBJECT (window2, label53, "label53");
  GLADE_HOOKUP_OBJECT (window2, bt_gest_rdv_staff_adh, "bt_gest_rdv_staff_adh");
  GLADE_HOOKUP_OBJECT (window2, bt_inscri_seance_adh, "bt_inscri_seance_adh");
  GLADE_HOOKUP_OBJECT (window2, bt_gest_don_adh, "bt_gest_don_adh");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, image35, "image35");
  GLADE_HOOKUP_OBJECT (window2, bt_profil_adh, "bt_profil_adh");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *label3;
  GtkWidget *calcul_IMC_adh;
  GtkWidget *label4;
  GtkWidget *bt_ajout_donnee_adh;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label30;
  GtkWidget *label60;
  GtkWidget *label59;
  GtkWidget *bt_modif_donnee_adh;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label32;
  GtkWidget *bt_supp_donnee_adh;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label31;
  GtkWidget *bt_retour_adh;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label29;
  GtkWidget *label65;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("Gestion des donn\303\251es"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 160, 80);
  gtk_widget_set_size_request (treeview1, 472, 200);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 344, 368);
  gtk_widget_set_size_request (entry5, 96, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 520, 368);
  gtk_widget_set_size_request (entry6, 96, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label3 = gtk_label_new (_("Calculer votre IMC !"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 0, 384);
  gtk_widget_set_size_request (label3, 200, 25);

  calcul_IMC_adh = gtk_button_new_with_mnemonic (_("Calculer IMC:"));
  gtk_widget_show (calcul_IMC_adh);
  gtk_fixed_put (GTK_FIXED (fixed3), calcul_IMC_adh, 40, 416);
  gtk_widget_set_size_request (calcul_IMC_adh, 128, 40);

  label4 = gtk_label_new (_("."));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 176, 416);
  gtk_widget_set_size_request (label4, 144, 41);

  bt_ajout_donnee_adh = gtk_button_new ();
  gtk_widget_show (bt_ajout_donnee_adh);
  gtk_fixed_put (GTK_FIXED (fixed3), bt_ajout_donnee_adh, 176, 320);
  gtk_widget_set_size_request (bt_ajout_donnee_adh, 96, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (bt_ajout_donnee_adh), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox2), label30, FALSE, FALSE, 0);

  label60 = gtk_label_new (_("CIN"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed3), label60, 296, 376);
  gtk_widget_set_size_request (label60, 49, 17);

  label59 = gtk_label_new (_("CIN"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed3), label59, 472, 376);
  gtk_widget_set_size_request (label59, 49, 17);

  bt_modif_donnee_adh = gtk_button_new ();
  gtk_widget_show (bt_modif_donnee_adh);
  gtk_fixed_put (GTK_FIXED (fixed3), bt_modif_donnee_adh, 344, 320);
  gtk_widget_set_size_request (bt_modif_donnee_adh, 104, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (bt_modif_donnee_adh), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox4), label32, FALSE, FALSE, 0);

  bt_supp_donnee_adh = gtk_button_new ();
  gtk_widget_show (bt_supp_donnee_adh);
  gtk_fixed_put (GTK_FIXED (fixed3), bt_supp_donnee_adh, 512, 320);
  gtk_widget_set_size_request (bt_supp_donnee_adh, 104, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (bt_supp_donnee_adh), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox3), label31, FALSE, FALSE, 0);

  bt_retour_adh = gtk_button_new ();
  gtk_widget_show (bt_retour_adh);
  gtk_fixed_put (GTK_FIXED (fixed3), bt_retour_adh, 688, 8);
  gtk_widget_set_size_request (bt_retour_adh, 88, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (bt_retour_adh), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox1), label29, FALSE, FALSE, 0);

  label65 = gtk_label_new (_("."));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed3), label65, 384, 408);
  gtk_widget_set_size_request (label65, 224, 40);

  g_signal_connect ((gpointer) calcul_IMC_adh, "clicked",
                    G_CALLBACK (on_calcul_IMC_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_ajout_donnee_adh, "clicked",
                    G_CALLBACK (on_bt_ajout_donnee_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_modif_donnee_adh, "clicked",
                    G_CALLBACK (on_bt_modif_donnee_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_supp_donnee_adh, "clicked",
                    G_CALLBACK (on_bt_supp_donnee_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_retour_adh, "clicked",
                    G_CALLBACK (on_bt_retour_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window3, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window3, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window3, label3, "label3");
  GLADE_HOOKUP_OBJECT (window3, calcul_IMC_adh, "calcul_IMC_adh");
  GLADE_HOOKUP_OBJECT (window3, label4, "label4");
  GLADE_HOOKUP_OBJECT (window3, bt_ajout_donnee_adh, "bt_ajout_donnee_adh");
  GLADE_HOOKUP_OBJECT (window3, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window3, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window3, image2, "image2");
  GLADE_HOOKUP_OBJECT (window3, label30, "label30");
  GLADE_HOOKUP_OBJECT (window3, label60, "label60");
  GLADE_HOOKUP_OBJECT (window3, label59, "label59");
  GLADE_HOOKUP_OBJECT (window3, bt_modif_donnee_adh, "bt_modif_donnee_adh");
  GLADE_HOOKUP_OBJECT (window3, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window3, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window3, image4, "image4");
  GLADE_HOOKUP_OBJECT (window3, label32, "label32");
  GLADE_HOOKUP_OBJECT (window3, bt_supp_donnee_adh, "bt_supp_donnee_adh");
  GLADE_HOOKUP_OBJECT (window3, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window3, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window3, image3, "image3");
  GLADE_HOOKUP_OBJECT (window3, label31, "label31");
  GLADE_HOOKUP_OBJECT (window3, bt_retour_adh, "bt_retour_adh");
  GLADE_HOOKUP_OBJECT (window3, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window3, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window3, image1, "image1");
  GLADE_HOOKUP_OBJECT (window3, label29, "label29");
  GLADE_HOOKUP_OBJECT (window3, label65, "label65");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *entry_taille_adh;
  GtkWidget *entry_poids_adh;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *bt_valid_adh;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label52;
  GtkWidget *bt_retour1_adh;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label55;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("Poids id\303\251al"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  entry_taille_adh = gtk_entry_new ();
  gtk_widget_show (entry_taille_adh);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_taille_adh, 328, 112);
  gtk_widget_set_size_request (entry_taille_adh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_taille_adh), 8226);

  entry_poids_adh = gtk_entry_new ();
  gtk_widget_show (entry_poids_adh);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_poids_adh, 328, 176);
  gtk_widget_set_size_request (entry_poids_adh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_poids_adh), 8226);

  label5 = gtk_label_new (_("Taille (cm) :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 208, 104);
  gtk_widget_set_size_request (label5, 120, 33);

  label6 = gtk_label_new (_("Poids (kg) :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 232, 176);
  gtk_widget_set_size_request (label6, 72, 25);

  bt_valid_adh = gtk_button_new ();
  gtk_widget_show (bt_valid_adh);
  gtk_fixed_put (GTK_FIXED (fixed4), bt_valid_adh, 336, 232);
  gtk_widget_set_size_request (bt_valid_adh, 96, 37);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (bt_valid_adh), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Valider !"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox24), label52, FALSE, FALSE, 0);

  bt_retour1_adh = gtk_button_new ();
  gtk_widget_show (bt_retour1_adh);
  gtk_fixed_put (GTK_FIXED (fixed4), bt_retour1_adh, 640, 16);
  gtk_widget_set_size_request (bt_retour1_adh, 82, 40);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (bt_retour1_adh), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox27), label55, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bt_valid_adh, "clicked",
                    G_CALLBACK (on_bt_valid_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_retour1_adh, "clicked",
                    G_CALLBACK (on_bt_retour1_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, entry_taille_adh, "entry_taille_adh");
  GLADE_HOOKUP_OBJECT (window4, entry_poids_adh, "entry_poids_adh");
  GLADE_HOOKUP_OBJECT (window4, label5, "label5");
  GLADE_HOOKUP_OBJECT (window4, label6, "label6");
  GLADE_HOOKUP_OBJECT (window4, bt_valid_adh, "bt_valid_adh");
  GLADE_HOOKUP_OBJECT (window4, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window4, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window4, image24, "image24");
  GLADE_HOOKUP_OBJECT (window4, label52, "label52");
  GLADE_HOOKUP_OBJECT (window4, bt_retour1_adh, "bt_retour1_adh");
  GLADE_HOOKUP_OBJECT (window4, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window4, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window4, image27, "image27");
  GLADE_HOOKUP_OBJECT (window4, label55, "label55");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *objectif;
  GtkWidget *entry_poids_donnee_adh;
  GtkWidget *entry_cin_adh;
  GtkWidget *label9;
  GtkWidget *type;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label66;
  GtkWidget *bt_ajouter_donnee_adh;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label50;
  GtkWidget *bt_retour2_adh;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label51;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("Ajouter mes donn\303\251es"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  objectif = gtk_entry_new ();
  gtk_widget_show (objectif);
  gtk_fixed_put (GTK_FIXED (fixed5), objectif, 168, 240);
  gtk_widget_set_size_request (objectif, 456, 168);
  gtk_entry_set_invisible_char (GTK_ENTRY (objectif), 8226);

  entry_poids_donnee_adh = gtk_entry_new ();
  gtk_widget_show (entry_poids_donnee_adh);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_poids_donnee_adh, 280, 96);
  gtk_widget_set_size_request (entry_poids_donnee_adh, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_poids_donnee_adh), 8226);

  entry_cin_adh = gtk_entry_new ();
  gtk_widget_show (entry_cin_adh);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_cin_adh, 280, 48);
  gtk_widget_set_size_request (entry_cin_adh, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_adh), 8226);

  label9 = gtk_label_new (_("Objectif:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed5), label9, 344, 192);
  gtk_widget_set_size_request (label9, 80, 41);

  type = gtk_combo_box_entry_new_text ();
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed5), type, 280, 152);
  gtk_widget_set_size_request (type, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (type), _("Crossfit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type), _("Zumba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type), _("RTX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type), _("Bodypump"));

  label8 = gtk_label_new (_("Type:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed5), label8, 208, 152);
  gtk_widget_set_size_request (label8, 64, 33);

  label7 = gtk_label_new (_("Poids:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 208, 96);
  gtk_widget_set_size_request (label7, 56, 25);

  label66 = gtk_label_new (_("cin:"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed5), label66, 216, 56);
  gtk_widget_set_size_request (label66, 48, 16);

  bt_ajouter_donnee_adh = gtk_button_new ();
  gtk_widget_show (bt_ajouter_donnee_adh);
  gtk_fixed_put (GTK_FIXED (fixed5), bt_ajouter_donnee_adh, 344, 416);
  gtk_widget_set_size_request (bt_ajouter_donnee_adh, 120, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (bt_ajouter_donnee_adh), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Ajouter !"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox22), label50, FALSE, FALSE, 0);

  bt_retour2_adh = gtk_button_new ();
  gtk_widget_show (bt_retour2_adh);
  gtk_fixed_put (GTK_FIXED (fixed5), bt_retour2_adh, 592, 16);
  gtk_widget_set_size_request (bt_retour2_adh, 90, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (bt_retour2_adh), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox23), label51, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bt_ajouter_donnee_adh, "clicked",
                    G_CALLBACK (on_bt_ajouter_donnee_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_retour2_adh, "clicked",
                    G_CALLBACK (on_bt_retour2_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, objectif, "objectif");
  GLADE_HOOKUP_OBJECT (window5, entry_poids_donnee_adh, "entry_poids_donnee_adh");
  GLADE_HOOKUP_OBJECT (window5, entry_cin_adh, "entry_cin_adh");
  GLADE_HOOKUP_OBJECT (window5, label9, "label9");
  GLADE_HOOKUP_OBJECT (window5, type, "type");
  GLADE_HOOKUP_OBJECT (window5, label8, "label8");
  GLADE_HOOKUP_OBJECT (window5, label7, "label7");
  GLADE_HOOKUP_OBJECT (window5, label66, "label66");
  GLADE_HOOKUP_OBJECT (window5, bt_ajouter_donnee_adh, "bt_ajouter_donnee_adh");
  GLADE_HOOKUP_OBJECT (window5, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window5, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window5, image22, "image22");
  GLADE_HOOKUP_OBJECT (window5, label50, "label50");
  GLADE_HOOKUP_OBJECT (window5, bt_retour2_adh, "bt_retour2_adh");
  GLADE_HOOKUP_OBJECT (window5, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window5, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window5, image23, "image23");
  GLADE_HOOKUP_OBJECT (window5, label51, "label51");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed6;
  GtkWidget *treeview2;
  GtkWidget *entry12_adh;
  GtkWidget *bt_inscrip_seance_adh;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label33;
  GtkWidget *bt_supp2_seance_adh;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label35;
  GtkWidget *label69;
  GtkWidget *bt_retour3_adh;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label36;
  GtkWidget *label70_adh;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 216, 80);
  gtk_widget_set_size_request (treeview2, 344, 192);

  entry12_adh = gtk_entry_new ();
  gtk_widget_show (entry12_adh);
  gtk_fixed_put (GTK_FIXED (fixed6), entry12_adh, 512, 328);
  gtk_widget_set_size_request (entry12_adh, 80, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12_adh), 8226);

  bt_inscrip_seance_adh = gtk_button_new ();
  gtk_widget_show (bt_inscrip_seance_adh);
  gtk_fixed_put (GTK_FIXED (fixed6), bt_inscrip_seance_adh, 184, 320);
  gtk_widget_set_size_request (bt_inscrip_seance_adh, 104, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (bt_inscrip_seance_adh), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Inscription"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox5), label33, FALSE, FALSE, 0);

  bt_supp2_seance_adh = gtk_button_new ();
  gtk_widget_show (bt_supp2_seance_adh);
  gtk_fixed_put (GTK_FIXED (fixed6), bt_supp2_seance_adh, 336, 320);
  gtk_widget_set_size_request (bt_supp2_seance_adh, 104, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (bt_supp2_seance_adh), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox7), label35, FALSE, FALSE, 0);

  label69 = gtk_label_new (_("Num"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed6), label69, 464, 328);
  gtk_widget_set_size_request (label69, 49, 17);

  bt_retour3_adh = gtk_button_new ();
  gtk_widget_show (bt_retour3_adh);
  gtk_fixed_put (GTK_FIXED (fixed6), bt_retour3_adh, 656, 16);
  gtk_widget_set_size_request (bt_retour3_adh, 96, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (bt_retour3_adh), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox8), label36, FALSE, FALSE, 0);

  label70_adh = gtk_label_new (_("."));
  gtk_widget_show (label70_adh);
  gtk_fixed_put (GTK_FIXED (fixed6), label70_adh, 488, 368);
  gtk_widget_set_size_request (label70_adh, 136, 33);

  g_signal_connect ((gpointer) bt_inscrip_seance_adh, "clicked",
                    G_CALLBACK (on_bt_inscrip_seance_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_supp2_seance_adh, "clicked",
                    G_CALLBACK (on_bt_supp2_seance_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_retour3_adh, "clicked",
                    G_CALLBACK (on_bt_retour3_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window6, entry12_adh, "entry12_adh");
  GLADE_HOOKUP_OBJECT (window6, bt_inscrip_seance_adh, "bt_inscrip_seance_adh");
  GLADE_HOOKUP_OBJECT (window6, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window6, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window6, image5, "image5");
  GLADE_HOOKUP_OBJECT (window6, label33, "label33");
  GLADE_HOOKUP_OBJECT (window6, bt_supp2_seance_adh, "bt_supp2_seance_adh");
  GLADE_HOOKUP_OBJECT (window6, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window6, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window6, image7, "image7");
  GLADE_HOOKUP_OBJECT (window6, label35, "label35");
  GLADE_HOOKUP_OBJECT (window6, label69, "label69");
  GLADE_HOOKUP_OBJECT (window6, bt_retour3_adh, "bt_retour3_adh");
  GLADE_HOOKUP_OBJECT (window6, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window6, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window6, image8, "image8");
  GLADE_HOOKUP_OBJECT (window6, label36, "label36");
  GLADE_HOOKUP_OBJECT (window6, label70_adh, "label70_adh");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed7;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *entry13;
  GtkWidget *calendar1;
  GtkWidget *label10;
  GtkWidget *label76;
  GtkWidget *coach;
  GtkWidget *heure;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *bt_retour4_adh;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label37;
  GtkWidget *bt_valid1_adh;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label38;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("Inscription"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7), fixed7);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed7), jour, 200, 320);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed7), mois, 376, 320);
  gtk_widget_set_size_request (mois, 64, 24);

  annee_adj = gtk_adjustment_new (1, 2018, 2025, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed7), annee, 552, 320);
  gtk_widget_set_size_request (annee, 60, 27);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed7), entry13, 296, 88);
  gtk_widget_set_size_request (entry13, 232, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed7), calendar1, 208, 368);
  gtk_widget_set_size_request (calendar1, 408, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label10 = gtk_label_new (_("Nom coach"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed7), label10, 200, 152);
  gtk_widget_set_size_request (label10, 80, 33);

  label76 = gtk_label_new (_("Num"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed7), label76, 232, 104);
  gtk_widget_set_size_request (label76, 49, 17);

  coach = gtk_combo_box_entry_new_text ();
  gtk_widget_show (coach);
  gtk_fixed_put (GTK_FIXED (fixed7), coach, 296, 152);
  gtk_widget_set_size_request (coach, 232, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (coach), _("hamza"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (coach), _("nadia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (coach), _("lotfi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (coach), _("zohra"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (coach), _("wassim"));

  heure = gtk_combo_box_entry_new_text ();
  gtk_widget_show (heure);
  gtk_fixed_put (GTK_FIXED (fixed7), heure, 296, 224);
  gtk_widget_set_size_request (heure, 229, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure), _("8-10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure), _("10-12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure), _("12-14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure), _("14-16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure), _("16-18"));

  label11 = gtk_label_new (_("Heure"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed7), label11, 240, 232);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("Jour"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed7), label12, 200, 296);
  gtk_widget_set_size_request (label12, 49, 17);

  label14 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed7), label14, 560, 296);
  gtk_widget_set_size_request (label14, 49, 17);

  label13 = gtk_label_new (_("Mois"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed7), label13, 384, 296);
  gtk_widget_set_size_request (label13, 49, 17);

  bt_retour4_adh = gtk_button_new ();
  gtk_widget_show (bt_retour4_adh);
  gtk_fixed_put (GTK_FIXED (fixed7), bt_retour4_adh, 24, 8);
  gtk_widget_set_size_request (bt_retour4_adh, 104, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (bt_retour4_adh), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox9), label37, FALSE, FALSE, 0);

  bt_valid1_adh = gtk_button_new ();
  gtk_widget_show (bt_valid1_adh);
  gtk_fixed_put (GTK_FIXED (fixed7), bt_valid1_adh, 584, 16);
  gtk_widget_set_size_request (bt_valid1_adh, 104, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (bt_valid1_adh), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox10), label38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bt_retour4_adh, "clicked",
                    G_CALLBACK (on_bt_retour4_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_valid1_adh, "clicked",
                    G_CALLBACK (on_bt_valid1_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7, jour, "jour");
  GLADE_HOOKUP_OBJECT (window7, mois, "mois");
  GLADE_HOOKUP_OBJECT (window7, annee, "annee");
  GLADE_HOOKUP_OBJECT (window7, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (window7, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (window7, label10, "label10");
  GLADE_HOOKUP_OBJECT (window7, label76, "label76");
  GLADE_HOOKUP_OBJECT (window7, coach, "coach");
  GLADE_HOOKUP_OBJECT (window7, heure, "heure");
  GLADE_HOOKUP_OBJECT (window7, label11, "label11");
  GLADE_HOOKUP_OBJECT (window7, label12, "label12");
  GLADE_HOOKUP_OBJECT (window7, label14, "label14");
  GLADE_HOOKUP_OBJECT (window7, label13, "label13");
  GLADE_HOOKUP_OBJECT (window7, bt_retour4_adh, "bt_retour4_adh");
  GLADE_HOOKUP_OBJECT (window7, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window7, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window7, image9, "image9");
  GLADE_HOOKUP_OBJECT (window7, label37, "label37");
  GLADE_HOOKUP_OBJECT (window7, bt_valid1_adh, "bt_valid1_adh");
  GLADE_HOOKUP_OBJECT (window7, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window7, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window7, image10, "image10");
  GLADE_HOOKUP_OBJECT (window7, label38, "label38");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed8;
  GtkWidget *treeview3;
  GtkWidget *entry11;
  GtkWidget *label15;
  GtkWidget *bt_retour_staff_adh;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label39;
  GtkWidget *bt_ajouter1_rdv_adh;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label40;
  GtkWidget *bt_supp_rdv_adh;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label42;
  GtkWidget *label70;
  GtkWidget *label75;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("window8"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8), fixed8);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview3, 224, 64);
  gtk_widget_set_size_request (treeview3, 336, 280);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed8), entry11, 496, 368);
  gtk_widget_set_size_request (entry11, 96, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label15 = gtk_label_new (_("Gestion des RDV avec staff m\303\251dical"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed8), label15, 248, 16);
  gtk_widget_set_size_request (label15, 272, 41);

  bt_retour_staff_adh = gtk_button_new ();
  gtk_widget_show (bt_retour_staff_adh);
  gtk_fixed_put (GTK_FIXED (fixed8), bt_retour_staff_adh, 648, 16);
  gtk_widget_set_size_request (bt_retour_staff_adh, 82, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (bt_retour_staff_adh), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox11), label39, FALSE, FALSE, 0);

  bt_ajouter1_rdv_adh = gtk_button_new ();
  gtk_widget_show (bt_ajouter1_rdv_adh);
  gtk_fixed_put (GTK_FIXED (fixed8), bt_ajouter1_rdv_adh, 160, 368);
  gtk_widget_set_size_request (bt_ajouter1_rdv_adh, 104, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (bt_ajouter1_rdv_adh), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox12), label40, FALSE, FALSE, 0);

  bt_supp_rdv_adh = gtk_button_new ();
  gtk_widget_show (bt_supp_rdv_adh);
  gtk_fixed_put (GTK_FIXED (fixed8), bt_supp_rdv_adh, 312, 368);
  gtk_widget_set_size_request (bt_supp_rdv_adh, 104, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (bt_supp_rdv_adh), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox14), label42, FALSE, FALSE, 0);

  label70 = gtk_label_new (_("num"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed8), label70, 448, 376);
  gtk_widget_set_size_request (label70, 49, 17);

  label75 = gtk_label_new (_("."));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed8), label75, 472, 408);
  gtk_widget_set_size_request (label75, 144, 32);

  g_signal_connect ((gpointer) bt_retour_staff_adh, "clicked",
                    G_CALLBACK (on_bt_retour_staff_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_ajouter1_rdv_adh, "clicked",
                    G_CALLBACK (on_bt_ajouter1_rdv_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_supp_rdv_adh, "clicked",
                    G_CALLBACK (on_bt_supp_rdv_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window8, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window8, label15, "label15");
  GLADE_HOOKUP_OBJECT (window8, bt_retour_staff_adh, "bt_retour_staff_adh");
  GLADE_HOOKUP_OBJECT (window8, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window8, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window8, image11, "image11");
  GLADE_HOOKUP_OBJECT (window8, label39, "label39");
  GLADE_HOOKUP_OBJECT (window8, bt_ajouter1_rdv_adh, "bt_ajouter1_rdv_adh");
  GLADE_HOOKUP_OBJECT (window8, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window8, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window8, image12, "image12");
  GLADE_HOOKUP_OBJECT (window8, label40, "label40");
  GLADE_HOOKUP_OBJECT (window8, bt_supp_rdv_adh, "bt_supp_rdv_adh");
  GLADE_HOOKUP_OBJECT (window8, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window8, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window8, image14, "image14");
  GLADE_HOOKUP_OBJECT (window8, label42, "label42");
  GLADE_HOOKUP_OBJECT (window8, label70, "label70");
  GLADE_HOOKUP_OBJECT (window8, label75, "label75");

  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GtkWidget *fixed9;
  GtkObject *jour2_adj;
  GtkWidget *jour2;
  GtkObject *mois2_adj;
  GtkWidget *mois2;
  GtkObject *annee2_adj;
  GtkWidget *annee2;
  GtkWidget *num2;
  GtkWidget *calendar2;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *heure2;
  GtkWidget *label18;
  GtkWidget *staff2;
  GtkWidget *label17;
  GtkWidget *label77;
  GtkWidget *label16;
  GtkWidget *bt_valid2_adh;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label44;
  GtkWidget *bt_retour_rdv_adh;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label43;

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("window9"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window9), fixed9);

  jour2_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour2 = gtk_spin_button_new (GTK_ADJUSTMENT (jour2_adj), 1, 0);
  gtk_widget_show (jour2);
  gtk_fixed_put (GTK_FIXED (fixed9), jour2, 208, 296);
  gtk_widget_set_size_request (jour2, 60, 27);

  mois2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois2 = gtk_spin_button_new (GTK_ADJUSTMENT (mois2_adj), 1, 0);
  gtk_widget_show (mois2);
  gtk_fixed_put (GTK_FIXED (fixed9), mois2, 352, 296);
  gtk_widget_set_size_request (mois2, 60, 27);

  annee2_adj = gtk_adjustment_new (2018, 2018, 2025, 1, 10, 10);
  annee2 = gtk_spin_button_new (GTK_ADJUSTMENT (annee2_adj), 1, 0);
  gtk_widget_show (annee2);
  gtk_fixed_put (GTK_FIXED (fixed9), annee2, 496, 296);
  gtk_widget_set_size_request (annee2, 60, 27);

  num2 = gtk_entry_new ();
  gtk_widget_show (num2);
  gtk_fixed_put (GTK_FIXED (fixed9), num2, 280, 72);
  gtk_widget_set_size_request (num2, 88, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (num2), 8226);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed9), calendar2, 168, 360);
  gtk_widget_set_size_request (calendar2, 456, 200);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label19 = gtk_label_new (_("Jour"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed9), label19, 200, 264);
  gtk_widget_set_size_request (label19, 49, 17);

  label20 = gtk_label_new (_("Mois"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed9), label20, 352, 264);
  gtk_widget_set_size_request (label20, 49, 17);

  label21 = gtk_label_new (_("Annee"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed9), label21, 496, 264);
  gtk_widget_set_size_request (label21, 49, 17);

  heure2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (heure2);
  gtk_fixed_put (GTK_FIXED (fixed9), heure2, 280, 176);
  gtk_widget_set_size_request (heure2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure2), _("8 -10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure2), _("10 -12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure2), _("12-14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure2), _("14-16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (heure2), _("16-18"));

  label18 = gtk_label_new (_("Heure"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed9), label18, 216, 184);
  gtk_widget_set_size_request (label18, 49, 17);

  staff2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (staff2);
  gtk_fixed_put (GTK_FIXED (fixed9), staff2, 280, 120);
  gtk_widget_set_size_request (staff2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (staff2), _("Nutriotionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (staff2), _("Kin\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (staff2), _("Di\303\251ticien"));

  label17 = gtk_label_new (_("Staff"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed9), label17, 216, 128);
  gtk_widget_set_size_request (label17, 49, 17);

  label77 = gtk_label_new (_("num"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed9), label77, 216, 80);
  gtk_widget_set_size_request (label77, 49, 17);

  label16 = gtk_label_new (_("Ajouter un RDV"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed9), label16, 280, 8);
  gtk_widget_set_size_request (label16, 160, 39);

  bt_valid2_adh = gtk_button_new ();
  gtk_widget_show (bt_valid2_adh);
  gtk_fixed_put (GTK_FIXED (fixed9), bt_valid2_adh, 640, 8);
  gtk_widget_set_size_request (bt_valid2_adh, 96, 45);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (bt_valid2_adh), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Valider "));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox16), label44, FALSE, FALSE, 0);

  bt_retour_rdv_adh = gtk_button_new ();
  gtk_widget_show (bt_retour_rdv_adh);
  gtk_fixed_put (GTK_FIXED (fixed9), bt_retour_rdv_adh, 16, 8);
  gtk_widget_set_size_request (bt_retour_rdv_adh, 90, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (bt_retour_rdv_adh), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox15), label43, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bt_valid2_adh, "clicked",
                    G_CALLBACK (on_bt_valid2_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_retour_rdv_adh, "clicked",
                    G_CALLBACK (on_bt_retour_rdv_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window9, jour2, "jour2");
  GLADE_HOOKUP_OBJECT (window9, mois2, "mois2");
  GLADE_HOOKUP_OBJECT (window9, annee2, "annee2");
  GLADE_HOOKUP_OBJECT (window9, num2, "num2");
  GLADE_HOOKUP_OBJECT (window9, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (window9, label19, "label19");
  GLADE_HOOKUP_OBJECT (window9, label20, "label20");
  GLADE_HOOKUP_OBJECT (window9, label21, "label21");
  GLADE_HOOKUP_OBJECT (window9, heure2, "heure2");
  GLADE_HOOKUP_OBJECT (window9, label18, "label18");
  GLADE_HOOKUP_OBJECT (window9, staff2, "staff2");
  GLADE_HOOKUP_OBJECT (window9, label17, "label17");
  GLADE_HOOKUP_OBJECT (window9, label77, "label77");
  GLADE_HOOKUP_OBJECT (window9, label16, "label16");
  GLADE_HOOKUP_OBJECT (window9, bt_valid2_adh, "bt_valid2_adh");
  GLADE_HOOKUP_OBJECT (window9, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window9, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window9, image16, "image16");
  GLADE_HOOKUP_OBJECT (window9, label44, "label44");
  GLADE_HOOKUP_OBJECT (window9, bt_retour_rdv_adh, "bt_retour_rdv_adh");
  GLADE_HOOKUP_OBJECT (window9, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window9, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window9, image15, "image15");
  GLADE_HOOKUP_OBJECT (window9, label43, "label43");

  return window9;
}

GtkWidget*
create_window12 (void)
{
  GtkWidget *window12;
  GtkWidget *fixed12;
  GtkWidget *entry7;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label64;
  GtkWidget *label63;
  GtkWidget *comboboxentry1;
  GtkWidget *label62;
  GtkWidget *label61;
  GtkWidget *label67;
  GtkWidget *bt_retour5_adh;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label73;
  GtkWidget *bt_modif1_adh;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label74;

  window12 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window12), _("window12"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window12), fixed12);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed12), entry7, 272, 120);
  gtk_widget_set_size_request (entry7, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed12), entry9, 160, 272);
  gtk_widget_set_size_request (entry9, 440, 208);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed12), entry10, 272, 72);
  gtk_widget_set_size_request (entry10, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label64 = gtk_label_new (_("."));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed12), label64, 560, 344);
  gtk_widget_set_size_request (label64, 144, 32);

  label63 = gtk_label_new (_("objectif"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed12), label63, 336, 232);
  gtk_widget_set_size_request (label63, 65, 25);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry1, 272, 168);
  gtk_widget_set_size_request (comboboxentry1, 208, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Crossfit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Zumba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("RTX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Body pump"));

  label62 = gtk_label_new (_("type"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed12), label62, 216, 176);
  gtk_widget_set_size_request (label62, 49, 17);

  label61 = gtk_label_new (_("poids"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed12), label61, 216, 120);
  gtk_widget_set_size_request (label61, 49, 17);

  label67 = gtk_label_new (_("cin"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed12), label67, 216, 72);
  gtk_widget_set_size_request (label67, 49, 17);

  bt_retour5_adh = gtk_button_new ();
  gtk_widget_show (bt_retour5_adh);
  gtk_fixed_put (GTK_FIXED (fixed12), bt_retour5_adh, 640, 16);
  gtk_widget_set_size_request (bt_retour5_adh, 96, 48);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (bt_retour5_adh), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox30), label73, FALSE, FALSE, 0);

  bt_modif1_adh = gtk_button_new ();
  gtk_widget_show (bt_modif1_adh);
  gtk_fixed_put (GTK_FIXED (fixed12), bt_modif1_adh, 320, 488);
  gtk_widget_set_size_request (bt_modif1_adh, 128, 37);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (bt_modif1_adh), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox31), label74, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bt_retour5_adh, "clicked",
                    G_CALLBACK (on_bt_retour5_adh_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_modif1_adh, "clicked",
                    G_CALLBACK (on_bt_modif1_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window12, window12, "window12");
  GLADE_HOOKUP_OBJECT (window12, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window12, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window12, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window12, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window12, label64, "label64");
  GLADE_HOOKUP_OBJECT (window12, label63, "label63");
  GLADE_HOOKUP_OBJECT (window12, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window12, label62, "label62");
  GLADE_HOOKUP_OBJECT (window12, label61, "label61");
  GLADE_HOOKUP_OBJECT (window12, label67, "label67");
  GLADE_HOOKUP_OBJECT (window12, bt_retour5_adh, "bt_retour5_adh");
  GLADE_HOOKUP_OBJECT (window12, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window12, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window12, image30, "image30");
  GLADE_HOOKUP_OBJECT (window12, label73, "label73");
  GLADE_HOOKUP_OBJECT (window12, bt_modif1_adh, "bt_modif1_adh");
  GLADE_HOOKUP_OBJECT (window12, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window12, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (window12, image31, "image31");
  GLADE_HOOKUP_OBJECT (window12, label74, "label74");

  return window12;
}

GtkWidget*
create_window13 (void)
{
  GtkWidget *window13;
  GtkWidget *fixed13;
  GtkWidget *entry_nom_adh;
  GtkWidget *entry_prenom_adh;
  GtkWidget *entry_ddn_adh;
  GtkWidget *entry_mail_adh;
  GtkWidget *entry_cin_adh;
  GtkWidget *entry_adresse_adh;
  GtkWidget *label81;
  GtkWidget *label80;
  GtkWidget *label82;
  GtkWidget *label79;
  GtkWidget *label78;
  GtkWidget *label87;
  GtkWidget *image32;
  GtkWidget *label89;
  GtkWidget *bt_retour_profil_adh;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image33;
  GtkWidget *label88;

  window13 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window13), _("window13"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (window13), fixed13);

  entry_nom_adh = gtk_entry_new ();
  gtk_widget_show (entry_nom_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_nom_adh, 560, 120);
  gtk_widget_set_size_request (entry_nom_adh, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry_nom_adh), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry_nom_adh), _("Haribi"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_adh), 8226);

  entry_prenom_adh = gtk_entry_new ();
  gtk_widget_show (entry_prenom_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_prenom_adh, 560, 184);
  gtk_widget_set_size_request (entry_prenom_adh, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry_prenom_adh), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry_prenom_adh), _("eya"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_adh), 8226);

  entry_ddn_adh = gtk_entry_new ();
  gtk_widget_show (entry_ddn_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_ddn_adh, 560, 240);
  gtk_widget_set_size_request (entry_ddn_adh, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry_ddn_adh), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry_ddn_adh), _("30/10/1996"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ddn_adh), 8226);

  entry_mail_adh = gtk_entry_new ();
  gtk_widget_show (entry_mail_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_mail_adh, 560, 304);
  gtk_widget_set_size_request (entry_mail_adh, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry_mail_adh), _("eya.haribi@esprit.tn"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mail_adh), 8226);

  entry_cin_adh = gtk_entry_new ();
  gtk_widget_show (entry_cin_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_cin_adh, 560, 376);
  gtk_widget_set_size_request (entry_cin_adh, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry_cin_adh), _("11375753"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_adh), 8226);

  entry_adresse_adh = gtk_entry_new ();
  gtk_widget_show (entry_adresse_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_adresse_adh, 560, 440);
  gtk_widget_set_size_request (entry_adresse_adh, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry_adresse_adh), _("8 rue de tunis"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adresse_adh), 8226);

  label81 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed13), label81, 504, 376);
  gtk_widget_set_size_request (label81, 49, 17);

  label80 = gtk_label_new (_("Email:"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed13), label80, 496, 312);
  gtk_widget_set_size_request (label80, 49, 17);

  label82 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed13), label82, 488, 448);
  gtk_widget_set_size_request (label82, 64, 17);

  label79 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed13), label79, 408, 248);
  gtk_widget_set_size_request (label79, 136, 16);

  label78 = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed13), label78, 456, 192);
  gtk_widget_set_size_request (label78, 89, 16);

  label87 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed13), label87, 480, 120);
  gtk_widget_set_size_request (label87, 49, 17);

  image32 = create_pixmap (window13, "my photo(1).jpg");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed13), image32, 32, 16);
  gtk_widget_set_size_request (image32, 360, 576);

  label89 = gtk_label_new (_("Mon profil"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed13), label89, 520, 8);
  gtk_widget_set_size_request (label89, 200, 102);
  gtk_misc_set_alignment (GTK_MISC (label89), 0.5, 0.49);

  bt_retour_profil_adh = gtk_button_new ();
  gtk_widget_show (bt_retour_profil_adh);
  gtk_fixed_put (GTK_FIXED (fixed13), bt_retour_profil_adh, 424, 528);
  gtk_widget_set_size_request (bt_retour_profil_adh, 120, 40);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (bt_retour_profil_adh), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image33 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox32), image33, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox32), label88, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bt_retour_profil_adh, "clicked",
                    G_CALLBACK (on_bt_retour_profil_adh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window13, window13, "window13");
  GLADE_HOOKUP_OBJECT (window13, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window13, entry_nom_adh, "entry_nom_adh");
  GLADE_HOOKUP_OBJECT (window13, entry_prenom_adh, "entry_prenom_adh");
  GLADE_HOOKUP_OBJECT (window13, entry_ddn_adh, "entry_ddn_adh");
  GLADE_HOOKUP_OBJECT (window13, entry_mail_adh, "entry_mail_adh");
  GLADE_HOOKUP_OBJECT (window13, entry_cin_adh, "entry_cin_adh");
  GLADE_HOOKUP_OBJECT (window13, entry_adresse_adh, "entry_adresse_adh");
  GLADE_HOOKUP_OBJECT (window13, label81, "label81");
  GLADE_HOOKUP_OBJECT (window13, label80, "label80");
  GLADE_HOOKUP_OBJECT (window13, label82, "label82");
  GLADE_HOOKUP_OBJECT (window13, label79, "label79");
  GLADE_HOOKUP_OBJECT (window13, label78, "label78");
  GLADE_HOOKUP_OBJECT (window13, label87, "label87");
  GLADE_HOOKUP_OBJECT (window13, image32, "image32");
  GLADE_HOOKUP_OBJECT (window13, label89, "label89");
  GLADE_HOOKUP_OBJECT (window13, bt_retour_profil_adh, "bt_retour_profil_adh");
  GLADE_HOOKUP_OBJECT (window13, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window13, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window13, image33, "image33");
  GLADE_HOOKUP_OBJECT (window13, label88, "label88");

  return window13;
}

